image: "pytorch/pytorch:1.2-cuda10.0-cudnn7-devel"

before_script:
  - pip install --upgrade pip>=18.0.0
  - pip install -r requirements.txt
  - apt-get update && apt-get -y install libgtk2.0-dev

stages:
  - test

test:
  tags: 
    - kaolin
  stage: test
  script:
    - source setenv.sh
    - python setup.py develop
    - ./tests/examples/run/test_classification.sh
      #- flake8 --config=.flake8 .
      #- pytest --cov=kaolin/ tests/
